---
name: "Commit"
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: Ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
    name: Test the project
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --python ${{ matrix.python-version }} --dev
      - name: Build
        run: pipenv run invoke build
  push:
    name: Build and push the Docker images
    runs-on: Ubuntu-20.04
    needs: test
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --dev
      - name: Build the Docker images
        run: pipenv run invoke build
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish the Docker images
        run: pipenv run invoke publish
      - name: Publish the README
        uses: christian-korneck/update-container-description-action@d36005551adeaba9698d8d67a296bd16fa91f8e8
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          destination_container_repo: seiso/hai
          provider: dockerhub
          short_description: 'Your friendly neighborhood identity provider'
          readme_file: 'README.md'
